version: '3.9'

services:
  redis:
    container_name: bot-redis
    image: redis:7.2.3
    env_file:
      - ./.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    restart: always
    networks:
      - custom

  bot:
    container_name: bot
    build: .
    command: sh -c "python3 run.py"
    restart: always
    env_file: ./.env
    depends_on:
      - redis
    networks:
      - custom


networks:

  custom:
    driver: bridge
