version: '3.9'

services:
  redis:
    image: redis:latest
    command:
      - redis-server
    env_file:
      - ./.env
    ports:
      - ${REDISPORT}:${REDISPORT}
    expose:
      - ${REDISPORT}
    restart: always
    volumes:
      - redis_data:/data

  bot:
    build: .
    command: sh -c "python3 run.py"
    restart: always
    env_file: ./.env
    depends_on:
      - redis

volumes:
  redis_data: