version: '3.7'

services:
  redis:
    image: redis:latest
    command:
      - redis-server
    env_file:
      - ./.env
    expose:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  bot:
    build: .
    restart: always
    env_file: ./.env
    depends_on:
      - redis

volumes:
  redis_data: